# SPDX-FileCopyrightText: 2026 Scenario Inc.
# SPDX-License-Identifier: GPL-3.0-or-later
"""Scenario's icons as Blender icon_values: the modalities (image, video, audio, 3d, text) and the prompt tools
(dice = generate a new prompt, sparkles = rewrite, translate).

The PNGs in `scenario/icons/` are generated by `tools/make_icons.py`; they are loaded once into a preview collection
and used wherever a lane, tab, model row or prompt button needs its mark. `icon(name)` is 0 when nothing is loaded so
callers can fall back to a built-in icon."""
import logging
import pathlib

import bpy
import bpy.utils.previews

log = logging.getLogger("scenario.icons")

ICON_NAMES = ("image", "video", "audio", "3d", "text", "dice", "sparkles", "translate")
ICON_DIR = pathlib.Path(__file__).resolve().parent.parent / "icons"
BUILTIN = {"image": 'IMAGE_DATA', "video": 'FILE_MOVIE', "audio": 'SPEAKER', "3d": 'MESH_DATA', "text": 'FILE_TEXT',
           "dice": 'LIGHT_SUN', "sparkles": 'FILE_REFRESH', "translate": 'WORLD_DATA'}
_collection = None


def icon_path(name):
    return ICON_DIR / f"{name}.png"


def register():
    global _collection
    if _collection is not None:
        return
    _collection = bpy.utils.previews.new()
    for name in ICON_NAMES:
        path = icon_path(name)
        if not path.exists():
            log.warning("icon %s missing at %s", name, path)
            continue
        try:
            _collection.load(name, str(path), 'IMAGE')
        except (KeyError, RuntimeError) as err:
            log.warning("icon %s not loaded: %s", name, err)


def unregister():
    global _collection
    if _collection is not None:
        try:
            bpy.utils.previews.remove(_collection)
        except (KeyError, RuntimeError):
            pass
        _collection = None


def loaded(name):
    """True when the PNG is in the collection with pixels. In `--background` Blender allocates no icon ids, so
    `icon()` stays 0 there while this still reports the file as loaded."""
    if _collection is None or name not in _collection:
        return False
    try:
        return tuple(_collection[name].image_size)[0] > 0
    except (KeyError, RuntimeError, TypeError):
        return False


def icon(name):
    """icon_value for a modality name, 0 when not loaded or headless (use `builtin(name)` then)."""
    if _collection is None or name not in _collection:
        return 0
    try:
        return _collection[name].icon_id
    except (KeyError, RuntimeError):
        return 0


def builtin(name):
    return BUILTIN.get(name, 'QUESTION')


def kwargs(name):
    """Keyword arguments for layout.label / operator / prop: the custom icon when loaded, the built-in one otherwise."""
    value = icon(name)
    return {"icon_value": value} if value else {"icon": builtin(name)}
